name: Terraform Destroy (Manual)

on:
  workflow_dispatch: {}

env:
  AWS_REGION: us-east-1

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # use local state so we can destroy the S3 bucket defined in TF
      - name: Terraform Init (local state)
        run: terraform init -backend=false -input=false

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
